route:
  receiver: 'Default'
  group_interval: 15s
  repeat_interval: 1m
  group_by: ['alertname']
  group_wait: 15s

  routes:
  - receiver: 'AlertAPIBeer'
    match:
      team: developers-api

receivers:
- name: 'Default'
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookdefault'

- name: 'AlertAPIBeer'
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookapi'