global:
  scrape_interval:     15s
  scrape_timeout:      5s
  evaluation_interval: 30s

rule_files:
  - alerts.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    scrape_interval: 5s
    static_configs: 
      - targets: ['api:5000']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'
